# Imports

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from pycaret.regression import *

# Data Read-In

In [2]:
data = pd.read_csv("../../../extrucal_machine-learning/data/extrucal_dataset.csv")
data

,extruder_size,metering_depth,polymer_density,rpm,screw_pitch,flight_width,number_flight,throughput
0,80,7.2,1200,95,48.0,12.0,2,92.55
1,220,17.6,1300,75,154.0,13.2,1,4397.68
2,190,7.6,1400,95,323.0,36.1,2,3187.76
3,190,7.6,800,55,228.0,26.6,1,1008.12
4,60,1.8,800,10,48.0,10.8,1,2.72
...,...,...,...,...,...,...,...,...
1935355,40,3.2,1000,30,32.0,4.0,1,8.78
1935356,180,3.6,800,85,306.0,27.0,2,762.58
1935357,30,1.8,1100,60,30.0,2.7,1,7.89
1935358,70,6.3,1000,40,35.0,10.5,2,11.59
1935359,180,10.8,1050,45,306.0,30.6,2,1458.83

In [3]:
# To make these variable as "numeric"

data['polymer_density'] = data['polymer_density'].astype('float')
data['rpm'] = data['rpm'].astype('float')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1935360 entries, 0 to 1935359
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   extruder_size    int64
 1   metering_depth   float64
 2   polymer_density  float64
 3   rpm              float64
 4   screw_pitch      float64
 5   flight_width     float64
 6   number_flight    int64
 7   throughput       float64
dtypes: float64(6), int64(2)
memory usage: 118.1 MB

# Setup of a Simple Experiment without Logging

In [8]:
experiment = setup(data, target='throughput')

In [9]:
# Model Selection

model = compare_models(n_select = 1)

In [11]:
# Model Optimization

tuned_model = tune_model(model)

In [12]:
# Finalize model
finalized_model = finalize_model(tuned_model)

# save model to disk
save_model(finalized_model, 'lgbm_simple')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[],
                                       target='throughput', time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strat...
                                colsample_bytree=1.0, feature_fraction=0.8,
                                importance_type='split', learning_rate=0.2,
                                max_depth=-1, min_child_samples=11,
                                min_child_weight=0.001, min_split_gain=0.8,
                                n_estimators=250, n_jobs=-1, num_leaves=100,
                                objective=None, random_state=1041,
                                reg_alpha=0.05, reg_lambda=4, silent='warn',
                                subsample=1.0, subsample_for_bin=200000,
                                subsample_freq=0)]],
          verbose=False),
 'lgbm_simple.pkl')

# Setup of an Experiment with Logging

In [4]:
experiment = setup(
    data, 
    target='throughput',
    log_experiment=True,
    log_plots=True,
    experiment_name='extrucal'  # Need this to make this appear in MLflow
)

In [5]:
# Model Selection

model = compare_models(n_select = 1)

In [6]:
# Model Optimization

tuned_model = tune_model(model)

In [7]:
# Finalize model
finalized_model = finalize_model(tuned_model)

# save model to disk
save_model(finalized_model, 'catb_logging')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[], ml_usecase='regression',
                                       numerical_features=[],
                                       target='throughput', time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strat...
                 ('cluster_all', 'passthrough'),
                 ('dummy', Dummify(target='throughput')),
                 ('fix_perfect', Remove_100(target='throughput')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  <catboost.core.CatBoostRegressor object at 0x000002432D624AF0>]],
          verbose=False),
 'catb_logging.pkl')